### ISSUE TITLE
Not sure if working as intended...

### ISSUE THREAD

**Issue by ApoIIy0n** [VirusTotal/yara-x#210] opened 2024-10-04 13:06 UTC
I was trying to scan a simple text file which contains hello. with the following rule

```
rule SomeRule2
{
    meta:
        description = "hello"
        strength = "8"

    strings:
        $dz = { 68 65 6C 6C 6F }
        $a = "hello"

    condition:
        $dz or $a
}
```

however for some reason the plain text file does not get any match. So I thought ok perhaps I messed up somewhere in my code (have made a wrapper for c#) so I tried the yr.exe which is in the releases like this.

`yr scan namespace:Test.yara testfile.js`

then I got the following

`Error parsing config, using defaults: The system cannot find the file specified. (os error 2)
 in C:\Users\********\.yara-x.toml TOML file
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1 file(s) scanned in 0.0s. 0 file(s) matched.
`

So is there something I'm doing wrong, or what's going on here?

p.s. the textfile contains only contineously the word hello with spaces inbetween.
and rules do get triggered with my wrapper while scanning for cve's within executables for example..

**Comment by wxsBSD** [comment] 2024-10-04 13:26
Looks like @plusvic already committed a fix for the error message when not able to find a config file (sorry about that, I should have removed it myself).

As for the failure to match the file, I can't reproduce this. Are you sure testfile.js should match?

Thanks for catching the unnecessary error message though!

**Comment by ApoIIy0n** [comment] 2024-10-04 13:44
[
[testfile.txt](https://github.com/user-attachments/files/17259264/testfile.txt)
](url)

I am pretty sure the txt file (which i renamed back to .txt (was testing if it was the file extension perhaps..) should trigger the rule above.

**Comment by wxsBSD** [comment] 2024-10-04 13:58
It does match for me (this is using the latest commit on `main` branch):

```
wxs@mbp yara-x % ./target/debug/yr scan rules/hello.yara ~/Desktop/testfile.txt
SomeRule2 /Users/wxs/Desktop/testfile.txt
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1 file(s) scanned in 0.2s. 1 file(s) matched.
wxs@mbp yara-x % cat rules/hello.yara
rule SomeRule2
{
    meta:
        description = "hello"
        strength = "8"

    strings:
        $dz = { 68 65 6C 6C 6F }
        $a = "hello"

    condition:
        $dz or $a
}
wxs@mbp yara-x % ./target/debug/yr scan rules/hello.yara ~/Desktop/testfile.txt
SomeRule2 /Users/wxs/Desktop/testfile.txt
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1 file(s) scanned in 0.2s. 1 file(s) matched.
wxs@mbp yara-x %
```

Can you try double checking you're using the right rule with the right file?

**Closed** 2024-10-04 14:07 UTC
