### ISSUE TITLE
Panic while Scanning Directories w/ Macho Module

### ISSUE THREAD

**Issue by g-les** [VirusTotal/yara-x#141] opened 2024-06-18 20:06 UTC
Hi gang

was testing use of `macho` module to detect RPaths and would regularly get a Panic when scanning over directories, but no issue on individual files. It looks like panic is coming from https://github.com/VirusTotal/yara-x/blob/main/lib/src/modules/macho/parser.rs#L321 

here is the error 
```
thread '<unnamed>' panicked at lib/src/modules/macho/parser.rs:321:35:
range end index 449752 out of range for slice of length 13052
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

Full logs, on `yara-x-cli 0.4.0` 

```
$ ./Desktop/yr -V
yara-x-cli 0.4.0

$ ./Desktop/yr scan Desktop/macho.yar MAL_MacOS_WindowServer/abf5c526de4925de9d7a839822e4239dbf3e545a167d4d575957e2fb42f12642 
RPath: /Users/mahmed/myproj/wsclient/mbedtls-extproj-prefix/lib
rpath_miner MAL_MacOS_WindowServer/abf5c526de4925de9d7a839822e4239dbf3e545a167d4d575957e2fb42f12642
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1 file(s) scanned in 0.1s. 1 file(s) matched.

$ ./Desktop/yr scan Desktop/macho.yar MAL_MacOS_WindowServer/
thread '<unnamed>' panicked at lib/src/modules/macho/parser.rs:321:35:
range end index 449752 out of range for slice of length 13052
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by latonis** [comment] 2024-06-19 03:47
This was fixed in https://github.com/VirusTotal/yara-x/commit/48d799dd4f50502237ebd535657a3417e536324f.

![image](https://github.com/VirusTotal/yara-x/assets/6127011/4a4ad39a-42db-4052-8181-514a77d496ea)

It just hasn't made it into a new release yet :smile:

**Comment by plusvic** [comment] 2024-06-19 08:36
@latonis as you already noticed, the main issue reported here is already fixed, but while investigating I've found another issue.

The program panics at this line:
https://github.com/VirusTotal/yara-x/blob/44cb51772f540e6508d08b17d142d69188375d75/lib/src/modules/macho/parser.rs#L980

That's because `prefix.to_str().unwrap()` is converting a string read from the file to UTF-8, but the string may contain data that is not valid UTF-8.

This issue is reproducible while scanning file: `c931a1ded68d7222467726f30144ecd54a9882458ac99275e930136391afce67`

By the way, the reason why the panic only occurs while scanning directories is because the file causing the panic is not the reported one, but some other file in the same directory.

**Closed** 2024-06-28 07:38 UTC
